[package]
name = "smith-waterman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ssw"
path = "src/lib.rs"
crate-type = ["rlib", "dylib"]

[profile.release]
# lto = true
opt-level = 3
debug = true

[dependencies]
tabular = "0.2.0"
needletail = "0.5.1"
clap = { version = "3.2.13", features = ["derive"] }
pyo3 = "0.20.2"